[package]
name = "kll_throughput"
version = "0.1.0"
edition = "2021"

[dependencies]
asap_sketchlib = { path = "../../../../asap_sketchlib" }
sketch_oxide = "0.1.5"

[[bin]]
name = "kll_throughput"
path = "src/main.rs"

[[bin]]
name = "kll_throughput_query"
path = "src/bin/query.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
