[workspace]

[package]
name = "throughput-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
asap_sketchlib = { version = "0.2.1", features = ["experimental"] }

[[bin]]
name = "cs_lib_fixedmatrix_fast"
path = "src/bin/cs_lib_fixedmatrix_fast.rs"

[[bin]]
name = "kll"
path = "src/bin/kll.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
