column_num: 2
column_label: [key, value]
row_num: 200000

column_spec:
  - data_type: string
    distribution:
      kind: zipf
      skewness: 1.1
      population_size: 100000
      seed: 1

  - data_type: i64
    distribution:
      kind: uniform
      lower_bound: 1.0
      upper_bound: 100.0
      seed: 2
